import * as assert from 'assert'
import * as async_hooks from 'async_hooks'
import * as buffer from 'buffer'
import * as child_process from 'child_process'
import * as cluster from 'cluster'
import * as console from 'console'
import * as constants from 'constants'
import * as crypto from 'crypto'
import * as dgram from 'dgram'
import * as dns from 'dns'
import * as domain from 'domain'
import * as events from 'events'
import * as fs from 'fs'
import * as http from 'http'
import * as http2 from 'http2'
import * as https from 'https'
// import * as inspector from 'inspector'
import * as module from 'module'
import * as net from 'net'
import * as os from 'os'
import * as path from 'path'
import * as perf_hooks from 'perf_hooks'
import * as process from 'process'
import * as punycode from 'punycode'
import * as querystring from 'querystring'
import * as readline from 'readline'
import * as repl from 'repl'
import * as stream from 'stream'
// import * as string_decoder from 'string_decoder'
// import * as sys from 'sys'
import * as timers from 'timers'
import * as tls from 'tls'
import * as tty from 'tty'
import * as url from 'url'
import * as util from 'util'
import * as v8 from 'v8'
import * as vm from 'vm'
import * as zlib from 'zlib'
